(()=>{const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),KEY='coach-tactics-pro-v2';
const formats={'11v11':{n:11,f:['4-3-3','4-2-3-1','4-4-2','3-4-3','3-5-2']},'9v9':{n:9,f:['3-2-3','3-3-2','2-3-3']},'8v8':{n:8,f:['2-3-2','3-2-2']},'7v7':{n:7,f:['2-3-1','3-2-1','2-2-2']},'6v6':{n:6,f:['2-2-1','1-3-1','2-1-2']},'5v5':{n:5,f:['1-2-1','2-1-1']}};
function mkTeam(id,name,format,formation,count){return{id,name,format,formation,players:Array.from({length:count},(_,i)=>({id:id+'p'+i,name:'',role:i===0?'GK':'P'+i,number:i+1,position:i===0?'GK':'',foot:'Right',status:'Available'}))}}
function migrate(raw){if(!raw)return null;raw.library=raw.library||[];raw.matches=raw.matches||[];raw.teams?.forEach(t=>t.players?.forEach(p=>{p.position=p.position||p.role||'';p.foot=p.foot||'Right';p.status=p.status||'Available'}));return raw}
let data;try{data=migrate(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('coach-tactics-pro-v1')||'null'))}catch(e){}if(!data)data={teams:[mkTeam('oregon','Oregon SC','11v11','4-3-3',15),mkTeam('randos','Randos','7v7','2-3-1',11),mkTeam('spartak','Spartak','6v6','2-2-1',10)],active:'oregon',matches:[],library:[]};
let team=data.teams.find(t=>t.id===data.active)||data.teams[0],selected=null,scenes=[],activeScene=-1,drag=null,playing=false,playbackPaused=false,playbackSpeed=1,raf=0,drawing=null;
function coords(format,formation){if(format==='11v11'&&formation==='4-3-3')return[[90,325],[255,105],[260,245],[260,405],[255,545],[405,325],[505,225],[505,425],[680,105],[720,325],[680,545]];const rows={'9v9':[1,3,2,3],'8v8':[1,2,3,2],'7v7':[1,2,3,1],'6v6':[1,2,2,1],'5v5':[1,1,2,1]}[format]||[1,4,3,3],out=[];let i=0;rows.forEach((n,r)=>{let x=90+780*r/(rows.length-1);for(let j=0;j<n&&i<formats[format].n;j++,i++){let y=n===1?325:90+j*(470/(n-1));out.push([x,y])}});return out}
function freshBoard(){const c=coords(team.format,team.formation),n=formats[team.format].n;return{players:team.players.slice(0,n).map((p,i)=>({...p,x:c[i][0],y:c[i][1]})),ball:{x:500,y:325},opponents:[],showOpponent:false,laneMode:5,bias:'left',drawings:[]}}let board=freshBoard();
const save=()=>{data.active=team.id;localStorage.setItem(KEY,JSON.stringify(data))};const status=t=>$('#status').textContent=t;const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const safe=s=>String(s||'').trim().replace(/[^a-z0-9]+/gi,'_').replace(/^_+|_+$/g,'').slice(0,60)||'match';
function downloadJSON(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),700)}
function teamUI(){$('#teamSelect').innerHTML=data.teams.map(t=>`<option value="${esc(t.id)}"${t.id===team.id?' selected':''}>${esc(t.name)} · ${t.format}</option>`).join('');$('#teamName').value=team.name;$('#format').value=team.format;$('#formation').innerHTML=formats[team.format].f.map(f=>`<option${f===team.formation?' selected':''}>${f}</option>`).join('')}
function rosterUI(){const box=$('#roster');box.innerHTML='';team.players.forEach((p,i)=>{const d=document.createElement('div');d.className='item';let starter=board.players.some(x=>x.id===p.id);d.innerHTML=`<button class="pick">${starter?'●':'○'} ${esc(p.name||('Player '+(i+1)))} <span class="tiny">#${p.number} · ${esc(p.role)} · ${esc(p.status||'Available')}</span></button><button class="btn danger">×</button>`;d.querySelector('.pick').onclick=()=>{if(starter){selected=p.id;editor();draw()}else{subPlayerIntoLineup(p)}};d.querySelector('.danger').onclick=()=>{if(team.players.length<=formats[team.format].n)return status('You need enough players for this format.');team.players=team.players.filter(x=>x.id!==p.id);board.players=board.players.filter(x=>x.id!==p.id);save();all()};box.appendChild(d)});const bench=$('#bench');bench.innerHTML='';team.players.filter(p=>!board.players.some(x=>x.id===p.id)).forEach(p=>{const b=document.createElement('button');b.className='bench-chip';b.textContent=(p.name||'Unnamed')+' #'+p.number;b.onclick=()=>subPlayerIntoLineup(p);bench.appendChild(b)});if(!bench.children.length)bench.innerHTML='<span class="tiny">No extra players.</span>'}
function subPlayerIntoLineup(p){let target=selected&&board.players.find(x=>x.id===selected);if(!target)return status('Select a player on the field first, then tap a bench player to substitute.');let idx=board.players.findIndex(x=>x.id===target.id),old=board.players[idx],tp={...p,x:old.x,y:old.y};board.players[idx]=tp;selected=tp.id;rosterUI();draw();editor();status(`${p.name||'Player'} substituted into the lineup.`)}
function lanes(){let out='',h=610/5;if(board.laneMode===5){for(let i=1;i<5;i++)out+=`<line x1="20" x2="980" y1="${20+i*h}" y2="${20+i*h}" stroke="#fff" stroke-opacity=".25" stroke-width="2"/>`}else if(board.laneMode===3){let st=board.bias==='left'?0:board.bias==='center'?1:2;for(let i=0;i<3;i++)out+=`<rect x="20" y="${20+(st+i)*h}" width="960" height="${h}" fill="#ffd36a" fill-opacity=".13"/>`;for(let i=1;i<5;i++)out+=`<line x1="20" x2="980" y1="${20+i*h}" y2="${20+i*h}" stroke="#fff" stroke-opacity=".16" stroke-width="2"/>`}$('#lanes').innerHTML=out}
function svgPoint(e){let s=$('#pitch'),p=s.createSVGPoint();p.x=e.clientX;p.y=e.clientY;let m=s.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:500,y:325}}
function token(p,ours){const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('transform',`translate(${p.x} ${p.y})`);g.style.cursor='grab';const fill=ours?(p.id===selected?'#ffd26c':'#f28c28'):'#d7dde0',stroke=ours?'#6d3811':'#565e62',txt=ours?(p.name||p.role):'OPP';g.innerHTML=`<circle r="${ours?27:23}" fill="${fill}" stroke="${stroke}" stroke-width="${ours&&p.id===selected?5:3}"/><text text-anchor="middle" y="5" font-size="${ours?14:12}" font-weight="800" fill="#1d1712">${esc(txt).slice(0,9)}</text>${ours?`<text text-anchor="middle" y="43" font-size="13" font-weight="800" fill="#fff" stroke="#173e25" paint-order="stroke" stroke-width="3">${esc(p.role)} · #${p.number}</text>`:''}`;g.onpointerdown=e=>{if(e.shiftKey)return;e.preventDefault();drag=p.id;g.setPointerCapture(e.pointerId);if(ours){selected=p.id;editor();draw()}};g.onpointermove=e=>{if(drag!==p.id)return;let q=svgPoint(e);p.x=clamp(q.x,45,955);p.y=clamp(q.y,45,605);draw()};g.onpointerup=()=>drag=null;g.onclick=()=>{if(ours){selected=p.id;editor();draw()}};return g}
function drawDrawings(){$('#drawings').innerHTML=(board.drawings||[]).map(a=>`<line x1="${a.x1}" y1="${a.y1}" x2="${a.x2}" y2="${a.y2}" stroke="#ffe08a" stroke-width="5" stroke-linecap="round" marker-end="url(#arrowHead)"/>`).join('')}
function draw(){lanes();drawDrawings();let pl=$('#players');pl.innerHTML='';board.players.forEach(p=>pl.appendChild(token(p,true)));let ol=$('#opponents');ol.innerHTML='';if(board.showOpponent)board.opponents.forEach(o=>ol.appendChild(token(o,false)));let bl=$('#ball');bl.innerHTML='';const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('transform',`translate(${board.ball.x} ${board.ball.y})`);g.style.cursor='grab';g.innerHTML='<circle r="13" fill="#fff" stroke="#111" stroke-width="3"/>';g.onpointerdown=e=>{if(e.shiftKey)return;e.preventDefault();drag='ball';g.setPointerCapture(e.pointerId)};g.onpointermove=e=>{if(drag!=='ball')return;let q=svgPoint(e);board.ball.x=clamp(q.x,35,965);board.ball.y=clamp(q.y,35,615);draw()};g.onpointerup=()=>drag=null;bl.appendChild(g);$('#laneBtn').textContent=board.laneMode===5?'5 lanes':board.laneMode===3?'3 lanes':'Lanes off';$('#oppBtn').textContent=board.showOpponent?'Hide opponent':'Show opponent';$('#bias').value=board.bias}
function editor(){let p=board.players.find(x=>x.id===selected);$('#editor').hidden=!p;if(!p)return;$('#pName').value=p.name;$('#pRole').value=p.role;$('#pNum').value=p.number;$('#pPosition').value=p.position||'';$('#pFoot').value=p.foot||'Right';$('#pStatus').value=p.status||'Available'}
function scenesUI(){let b=$('#scenes');b.innerHTML=scenes.length?'':'<div class="tiny">No phases saved.</div>';let ind=$('#phaseIndicator');if(ind)ind.textContent=`Phase ${activeScene>=0?activeScene+1:0} / ${scenes.length}`;scenes.forEach((s,i)=>{let d=document.createElement('div');d.className='item '+(activeScene===i?'active':'');d.innerHTML=`<button class="pick">${i+1}. ${esc(s.name)} <span class="tiny">${esc(s.moment||'')}</span></button><span class="phase-actions"><button class="iconbtn up">↑</button><button class="iconbtn down">↓</button><button class="iconbtn dup">⧉</button><button class="iconbtn del">×</button></span>`;d.querySelector('.pick').onclick=()=>loadScene(i);d.querySelector('.up').onclick=()=>moveScene(i,-1);d.querySelector('.down').onclick=()=>moveScene(i,1);d.querySelector('.dup').onclick=()=>{scenes.splice(i+1,0,structuredClone(s));scenes[i+1].name+=' Copy';scenesUI()};d.querySelector('.del').onclick=()=>{scenes.splice(i,1);activeScene=-1;scenesUI()};b.appendChild(d)})}
function moveScene(i,dir){let j=i+dir;if(j<0||j>=scenes.length)return;[scenes[i],scenes[j]]=[scenes[j],scenes[i]];activeScene=j;scenesUI()}
function loadScene(i){let s=scenes[i];if(!s)return;board=structuredClone(s.board);activeScene=i;$('#phaseName').value=s.name;$('#phaseNotes').value=s.notes||'';$('#moment').value=s.moment||'Build Up';draw();rosterUI();scenesUI();status(`Phase ${i+1}/${scenes.length}: ${s.name}`)}
function matchesUI(){let b=$('#matches'),ms=data.matches.filter(m=>m.teamId===team.id);b.innerHTML=ms.length?'':'<div class="tiny">No saved match plans.</div>';ms.slice(0,15).forEach(m=>{let d=document.createElement('div');d.className='match-card';d.innerHTML=`<strong>${esc(m.opponent)}</strong><span class="tiny">${esc(m.date||'No date')} · ${esc(m.format)} · ${esc(m.formation)}</span><div class="tools" style="margin-bottom:0"><button class="btn open">Open</button><button class="btn dl">Download</button><button class="btn danger del">Delete</button></div>`;d.querySelector('.open').onclick=()=>openMatch(m);d.querySelector('.dl').onclick=()=>downloadMatch(m);d.querySelector('.del').onclick=()=>{data.matches=data.matches.filter(x=>x.id!==m.id);save();matchesUI()};b.appendChild(d)})}
function openMatch(m){scenes=structuredClone(m.scenes||[]);$('#matchOpponent').value=m.opponent;$('#matchDate').value=m.date||'';$('#venue').value=m.venue||'';$('#competition').value=m.competition||'';$('#objectives').value=m.objectives||'';$('#setPieces').value=m.setPieces||'';$('#mdOpponent').value=m.opponent||'';$('#mdCompetition').value=m.competition||'';$('#mdPriorities').value=m.objectives||'';if(scenes[0])loadScene(0);scenesUI();status('Match plan loaded.')}
function libraryUI(){let b=$('#libraryItems');b.innerHTML=data.library.length?'':'<div class="tiny">No tactical sequences saved.</div>';data.library.forEach((x,i)=>{let d=document.createElement('div');d.className='library-card';d.innerHTML=`<strong>${esc(x.name)}</strong><div class="tiny">${esc(x.teamName)} · ${x.scenes.length} phases · ${esc(x.format)}</div><div class="tools" style="margin-bottom:0"><button class="btn load">Load</button><button class="btn danger del">Delete</button></div>`;d.querySelector('.load').onclick=()=>{scenes=structuredClone(x.scenes);activeScene=-1;if(scenes[0])loadScene(0);scenesUI();showView('tactics');status('Tactical sequence loaded.')};d.querySelector('.del').onclick=()=>{data.library.splice(i,1);save();libraryUI()};b.appendChild(d)})}
function all(){teamUI();rosterUI();draw();scenesUI();matchesUI();libraryUI();editor()}
function applyFormation(){team.formation=$('#formation').value;let c=coords(team.format,team.formation);board.players.forEach((p,i)=>{p.x=c[i]?.[0]||500;p.y=c[i]?.[1]||325});save();draw();status('Formation applied.')}
function opponent(){board.showOpponent=!board.showOpponent;if(board.showOpponent&&!board.opponents.length){let c=coords(team.format,team.formation);board.opponents=c.map((q,i)=>({id:'o'+i,x:1000-q[0],y:q[1],role:'OPP',number:i+1,name:''}))}draw()}
function snap(){return{name:($('#phaseName').value.trim()||`Phase ${scenes.length+1}`).slice(0,50),moment:$('#moment').value,notes:$('#phaseNotes').value.slice(0,1500),board:structuredClone(board)}}
function anim(target,dur=900){return new Promise(res=>{let elapsed=0,last=performance.now(),fp=structuredClone(board.players),fb={...board.ball};function step(now){if(!playing)return res();if(playbackPaused){last=now;raf=requestAnimationFrame(step);return}elapsed+=(now-last)*playbackSpeed;last=now;let raw=clamp(elapsed/dur,0,1),t=raw*raw*(3-2*raw);board.players.forEach((p,i)=>{let q=target.players.find(x=>x.id===p.id)||target.players[i]||p,a=fp[i]||p;p.x=a.x+(q.x-a.x)*t;p.y=a.y+(q.y-a.y)*t});board.ball.x=fb.x+(target.ball.x-fb.x)*t;board.ball.y=fb.y+(target.ball.y-fb.y)*t;draw();if(raw<1)raf=requestAnimationFrame(step);else{board=structuredClone(target);res()}}raf=requestAnimationFrame(step)})}
function setPaused(value){playbackPaused=value;let b=$('#pause');if(b)b.textContent=playbackPaused?'▶ Resume':'⏸ Pause';status(playbackPaused?`Paused at phase ${activeScene+1}/${scenes.length}. Use ← / → to step.`:'Animation resumed.')}
function stopPlayback(message='Animation stopped.'){playing=false;playbackPaused=false;if(raf)cancelAnimationFrame(raf);let b=$('#pause');if(b)b.textContent='⏸ Pause';if(message)status(message)}
function stepPhase(dir){if(!scenes.length)return status('Save at least one phase first.');if(playing)setPaused(true);let next=activeScene<0?(dir>0?0:scenes.length-1):clamp(activeScene+dir,0,scenes.length-1);loadScene(next)}
async function play(){if(scenes.length<2)return status('Save at least two phases first.');if(playing){if(playbackPaused)setPaused(false);return}playing=true;playbackPaused=false;$('#pause').textContent='⏸ Pause';let start=activeScene>=0?activeScene:0;for(let i=start;i<scenes.length&&playing;i++){activeScene=i;scenesUI();status(`Playing phase ${i+1}/${scenes.length}: ${scenes[i].name} · ${playbackSpeed}×`);await anim(scenes[i].board);if(!playing)break;let wait=0;while(wait<350&&playing){if(!playbackPaused)wait+=50;await new Promise(r=>setTimeout(r,50))}}if(playing){playing=false;playbackPaused=false;$('#pause').textContent='⏸ Pause';status('Sequence complete.')}}
function matchObject(){return{id:'m'+Date.now(),fileType:'CoachTacticsProMatchPlan',version:2,createdAt:new Date().toISOString(),teamId:team.id,teamName:team.name,opponent:$('#matchOpponent').value.trim()||'Opponent',date:$('#matchDate').value,venue:$('#venue').value.trim(),competition:$('#competition').value.trim(),objectives:$('#objectives').value,setPieces:$('#setPieces').value,format:team.format,formation:team.formation,roster:structuredClone(team.players),startingLineup:structuredClone(board.players),scenes:structuredClone(scenes),matchDay:{scoreUs:Number($('#scoreUs').value)||0,scoreThem:Number($('#scoreThem').value)||0,priorities:$('#mdPriorities').value,notes:$('#mdNotes').value}}}
function downloadMatch(m){let name=`${safe(m.teamName||team.name)}_vs_${safe(m.opponent)}_${m.date||'undated'}.matchplan.json`;downloadJSON(m,name)}
function saveMatch(){let m=matchObject();data.matches.unshift(m);save();matchesUI();downloadMatch(m);status('Match plan saved locally and downloaded as a file.')}
function importMatch(file){let r=new FileReader();r.onload=()=>{try{let m=JSON.parse(r.result);if(!m||m.fileType!=='CoachTacticsProMatchPlan')throw 0;data.matches.unshift(m);save();matchesUI();openMatch(m);status('Match plan imported.')}catch(_){status('That is not a valid Coach Tactics Pro match-plan file.')}};r.readAsText(file)}
function saveLibrary(){if(!scenes.length)return status('Save at least one phase first.');let name=($('#libraryName').value.trim()||$('#phaseName').value.trim()||'Tactical sequence').slice(0,60);data.library.unshift({id:'lib'+Date.now(),name,teamName:team.name,teamId:team.id,format:team.format,formation:team.formation,scenes:structuredClone(scenes)});save();libraryUI();status('Sequence saved to Tactical Library.')}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==`view-${name}`);document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name))}
function setConnection(){let c=$('#connection'),on=navigator.onLine;c.textContent=on?'Online':'Offline';c.className='btn '+(on?'online-pill':'offline-pill')}
$('#pitch').addEventListener('pointerdown',e=>{if(!e.shiftKey)return;let p=svgPoint(e);drawing={x1:p.x,y1:p.y,x2:p.x,y2:p.y};e.preventDefault()});$('#pitch').addEventListener('pointermove',e=>{if(!drawing)return;let p=svgPoint(e);drawing.x2=p.x;drawing.y2=p.y;let temp=[...(board.drawings||[]),drawing];$('#drawings').innerHTML=temp.map(a=>`<line x1="${a.x1}" y1="${a.y1}" x2="${a.x2}" y2="${a.y2}" stroke="#ffe08a" stroke-width="5" stroke-linecap="round" marker-end="url(#arrowHead)"/>`).join('')});$('#pitch').addEventListener('pointerup',()=>{if(drawing){board.drawings=board.drawings||[];board.drawings.push({...drawing});drawing=null;drawDrawings()}});
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showView(t.dataset.view));
$('#teamSelect').onchange=e=>{data.active=e.target.value;team=data.teams.find(t=>t.id===data.active);board=freshBoard();scenes=[];selected=null;save();all()};
$('#addTeam').onclick=()=>{let name=prompt('Team name');if(!name)return;let fmt=prompt('Format: 11v11, 9v9, 8v8, 7v7, 6v6, or 5v5','7v7');if(!formats[fmt])return status('Unsupported format.');let id='t'+Date.now(),t=mkTeam(id,name,fmt,formats[fmt].f[0],formats[fmt].n+4);data.teams.push(t);data.active=id;team=t;board=freshBoard();scenes=[];save();all()};
$('#delTeam').onclick=()=>{if(data.teams.length===1)return status('Keep at least one team.');if(!confirm(`Delete ${team.name}?`))return;data.teams=data.teams.filter(t=>t.id!==team.id);team=data.teams[0];data.active=team.id;board=freshBoard();scenes=[];save();all()};
$('#teamName').onchange=e=>{team.name=e.target.value.trim().slice(0,50)||team.name;save();teamUI()};$('#format').onchange=e=>{team.format=e.target.value;team.formation=formats[team.format].f[0];while(team.players.length<formats[team.format].n)team.players.push({id:team.id+'p'+Date.now()+team.players.length,name:'',role:'P'+team.players.length,number:team.players.length+1,position:'',foot:'Right',status:'Available'});board=freshBoard();scenes=[];save();all()};$('#formation').onchange=applyFormation;$('#applyFormation').onclick=applyFormation;$('#addPlayer').onclick=()=>{let i=team.players.length,p={id:team.id+'p'+Date.now(),name:'',role:'SUB',number:i+1,position:'',foot:'Right',status:'Available'};team.players.push(p);save();rosterUI()};$('#oppBtn').onclick=opponent;$('#laneBtn').onclick=()=>{board.laneMode=board.laneMode===5?3:board.laneMode===3?0:5;draw()};$('#bias').onchange=e=>{board.bias=e.target.value;draw()};$('#clearDrawings').onclick=()=>{board.drawings=[];drawDrawings()};
$('#savePhase').onclick=()=>{scenes.push(snap());activeScene=scenes.length-1;scenesUI();status('Phase saved.')};$('#play').onclick=play;$('#pause').onclick=()=>{if(!playing)return status('Start the animation first, or use ← / → to step through phases.');setPaused(!playbackPaused)};$('#stop').onclick=()=>stopPlayback();$('#prevPhase').onclick=()=>stepPhase(-1);$('#nextPhase').onclick=()=>stepPhase(1);$('#playbackSpeed').onchange=e=>{playbackSpeed=clamp(Number(e.target.value)||1,.25,2);status(`Playback speed: ${playbackSpeed}×`)};$('#saveLibrary').onclick=saveLibrary;$('#librarySaveCurrent').onclick=saveLibrary;
function syncPlayer(field,val){let p=board.players.find(x=>x.id===selected),q=team.players.find(x=>x.id===selected);if(!p)return;p[field]=val;if(q)q[field]=val;save();draw();rosterUI()}
$('#pName').oninput=e=>syncPlayer('name',e.target.value.slice(0,24));$('#pRole').oninput=e=>syncPlayer('role',e.target.value.slice(0,12)||'P');$('#pNum').oninput=e=>syncPlayer('number',clamp(parseInt(e.target.value||0),0,99));$('#pPosition').oninput=e=>syncPlayer('position',e.target.value.slice(0,16));$('#pFoot').onchange=e=>syncPlayer('foot',e.target.value);$('#pStatus').onchange=e=>syncPlayer('status',e.target.value);document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{let p=board.players.find(x=>x.id===selected);if(!p)return;let [dx,dy]=b.dataset.nudge.split(',').map(Number);p.x=clamp(p.x+dx,45,955);p.y=clamp(p.y+dy,45,605);draw()});
$('#saveMatch').onclick=saveMatch;$('#matchImport').onchange=e=>{let f=e.target.files[0];if(f)importMatch(f);e.target.value=''};
$('#exportBtn').onclick=()=>downloadJSON(data,'coach-tactics-pro-full-backup.json');$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let o=migrate(JSON.parse(r.result));if(!o||!Array.isArray(o.teams))throw 0;data=o;team=data.teams[0];data.active=team.id;board=freshBoard();scenes=[];save();all();status('Backup restored.')}catch(_){status('Invalid backup file.')}};r.readAsText(f);e.target.value=''};
document.addEventListener('keydown',e=>{let el=e.target,tag=el&&el.tagName;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT'||(el&&el.isContentEditable))return;if(e.key==='ArrowRight'){e.preventDefault();stepPhase(1)}else if(e.key==='ArrowLeft'){e.preventDefault();stepPhase(-1)}else if(e.code==='Space'){e.preventDefault();if(playing)setPaused(!playbackPaused);else play()}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});all();setConnection();status(navigator.onLine?'Ready · online':'Ready · offline');addEventListener('online',()=>{setConnection();status('Connection restored.')});addEventListener('offline',()=>{setConnection();status('Offline mode · local plans remain available.')});})();
