(()=>{const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),KEY='coach-tactics-pro-v1';
const formats={'11v11':{n:11,f:['4-3-3','4-2-3-1','4-4-2','3-4-3','3-5-2']},'9v9':{n:9,f:['3-2-3','3-3-2','2-3-3']},'8v8':{n:8,f:['2-3-2','3-2-2']},'7v7':{n:7,f:['2-3-1','3-2-1','2-2-2']},'6v6':{n:6,f:['2-2-1','1-3-1','2-1-2']},'5v5':{n:5,f:['1-2-1','2-1-1']}};
function mkTeam(id,name,format,formation,count){return{id,name,format,formation,players:Array.from({length:count},(_,i)=>({id:id+'p'+i,name:'',role:i===0?'GK':'P'+i,number:i+1}))}}
let data;try{data=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){}if(!data)data={teams:[mkTeam('oregon','Oregon SC','11v11','4-3-3',14),mkTeam('randos','Randos','7v7','2-3-1',10),mkTeam('spartak','Spartak','6v6','2-2-1',9)],active:'oregon',matches:[]};
let team=data.teams.find(t=>t.id===data.active)||data.teams[0],selected=null,scenes=[],activeScene=-1,drag=null,playing=false,raf=0;
function coords(format,formation){if(format==='11v11'&&formation==='4-3-3')return[[90,325],[255,105],[260,245],[260,405],[255,545],[405,325],[505,225],[505,425],[680,105],[720,325],[680,545]];const rows={'9v9':[1,3,2,3],'8v8':[1,2,3,2],'7v7':[1,2,3,1],'6v6':[1,2,2,1],'5v5':[1,1,2,1]}[format]||[1,4,3,3],out=[];let i=0;rows.forEach((n,r)=>{let x=90+780*r/(rows.length-1);for(let j=0;j<n&&i<formats[format].n;j++,i++){let y=n===1?325:90+j*(470/(n-1));out.push([x,y])}});return out}
function freshBoard(){const c=coords(team.format,team.formation),n=formats[team.format].n;return{players:team.players.slice(0,n).map((p,i)=>({...p,x:c[i][0],y:c[i][1]})),ball:{x:500,y:325},opponents:[],showOpponent:false,laneMode:5,bias:'left'}}let board=freshBoard();
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));const status=t=>$('#status').textContent=t;const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function teamUI(){$('#teamSelect').innerHTML=data.teams.map(t=>`<option value="${esc(t.id)}"${t.id===team.id?' selected':''}>${esc(t.name)} · ${t.format}</option>`).join('');$('#teamName').value=team.name;$('#format').value=team.format;$('#formation').innerHTML=formats[team.format].f.map(f=>`<option${f===team.formation?' selected':''}>${f}</option>`).join('');}
function rosterUI(){const box=$('#roster');box.innerHTML='';team.players.forEach((p,i)=>{const d=document.createElement('div');d.className='item';d.innerHTML=`<button class="pick">${esc(p.name||('Player '+(i+1)))} <span class="tiny">#${p.number} · ${esc(p.role)}</span></button><button class="btn danger">×</button>`;d.querySelector('.pick').onclick=()=>{if(board.players.some(x=>x.id===p.id)){selected=p.id;editor();draw()}else status('This player is currently a substitute.')};d.querySelector('.danger').onclick=()=>{if(team.players.length<=formats[team.format].n)return status('You need enough players for this format.');team.players=team.players.filter(x=>x.id!==p.id);board.players=board.players.filter(x=>x.id!==p.id);save();all()};box.appendChild(d)})}
function lanes(){let out='',h=610/5;if(board.laneMode===5){for(let i=1;i<5;i++)out+=`<line x1="20" x2="980" y1="${20+i*h}" y2="${20+i*h}" stroke="#fff" stroke-opacity=".25" stroke-width="2"/>`}else if(board.laneMode===3){let st=board.bias==='left'?0:board.bias==='center'?1:2;for(let i=0;i<3;i++)out+=`<rect x="20" y="${20+(st+i)*h}" width="960" height="${h}" fill="#ffd36a" fill-opacity=".13"/>`;for(let i=1;i<5;i++)out+=`<line x1="20" x2="980" y1="${20+i*h}" y2="${20+i*h}" stroke="#fff" stroke-opacity=".16" stroke-width="2"/>`}$('#lanes').innerHTML=out}
function svgPoint(e){let s=$('#pitch'),p=s.createSVGPoint();p.x=e.clientX;p.y=e.clientY;let m=s.getScreenCTM();return m?p.matrixTransform(m.inverse()):{x:500,y:325}}
function token(p,ours){const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('transform',`translate(${p.x} ${p.y})`);g.style.cursor='grab';const fill=ours?(p.id===selected?'#ffd26c':'#f28c28'):'#d7dde0',stroke=ours?'#6d3811':'#565e62',txt=ours?(p.name||p.role):'OPP';g.innerHTML=`<circle r="${ours?27:23}" fill="${fill}" stroke="${stroke}" stroke-width="${ours&&p.id===selected?5:3}"/><text text-anchor="middle" y="5" font-size="${ours?14:12}" font-weight="800" fill="#1d1712">${esc(txt).slice(0,9)}</text>${ours?`<text text-anchor="middle" y="43" font-size="13" font-weight="800" fill="#fff" stroke="#173e25" paint-order="stroke" stroke-width="3">${esc(p.role)} · #${p.number}</text>`:''}`;g.onpointerdown=e=>{e.preventDefault();drag=p.id;g.setPointerCapture(e.pointerId);if(ours){selected=p.id;editor();draw()}};g.onpointermove=e=>{if(drag!==p.id)return;let q=svgPoint(e);p.x=clamp(q.x,45,955);p.y=clamp(q.y,45,605);draw()};g.onpointerup=()=>drag=null;g.onclick=()=>{if(ours){selected=p.id;editor();draw()}};return g}
function draw(){lanes();let pl=$('#players');pl.innerHTML='';board.players.forEach(p=>pl.appendChild(token(p,true)));let ol=$('#opponents');ol.innerHTML='';if(board.showOpponent)board.opponents.forEach(o=>ol.appendChild(token(o,false)));let bl=$('#ball');bl.innerHTML='';const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.setAttribute('transform',`translate(${board.ball.x} ${board.ball.y})`);g.style.cursor='grab';g.innerHTML='<circle r="13" fill="#fff" stroke="#111" stroke-width="3"/>';g.onpointerdown=e=>{e.preventDefault();drag='ball';g.setPointerCapture(e.pointerId)};g.onpointermove=e=>{if(drag!=='ball')return;let q=svgPoint(e);board.ball.x=clamp(q.x,35,965);board.ball.y=clamp(q.y,35,615);draw()};g.onpointerup=()=>drag=null;bl.appendChild(g);$('#laneBtn').textContent=board.laneMode===5?'5 lanes':board.laneMode===3?'3 lanes':'Lanes off';$('#oppBtn').textContent=board.showOpponent?'Hide opponent':'Show opponent';$('#bias').value=board.bias}
function editor(){let p=board.players.find(x=>x.id===selected);$('#editor').hidden=!p;if(!p)return;$('#pName').value=p.name;$('#pRole').value=p.role;$('#pNum').value=p.number}
function scenesUI(){let b=$('#scenes');b.innerHTML=scenes.length?'':'<div class="tiny">No phases saved.</div>';scenes.forEach((s,i)=>{let d=document.createElement('div');d.className='item '+(activeScene===i?'active':'');d.innerHTML=`<button class="pick">${i+1}. ${esc(s.name)}</button><button class="btn danger">×</button>`;d.querySelector('.pick').onclick=()=>{board=structuredClone(s.board);activeScene=i;$('#phaseName').value=s.name;$('#phaseNotes').value=s.notes||'';draw();scenesUI()};d.querySelector('.danger').onclick=()=>{scenes.splice(i,1);activeScene=-1;scenesUI()};b.appendChild(d)})}
function matchesUI(){let b=$('#matches'),ms=data.matches.filter(m=>m.teamId===team.id);b.innerHTML=ms.length?'':'<div class="tiny">No saved match plans.</div>';ms.slice(0,10).forEach(m=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<button class="pick">${esc(m.opponent)} <span class="tiny">${esc(m.date||'No date')} · ${m.format}</span></button><button class="btn danger">×</button>`;d.querySelector('.pick').onclick=()=>{scenes=structuredClone(m.scenes||[]);$('#matchOpponent').value=m.opponent;$('#matchDate').value=m.date||'';$('#venue').value=m.venue||'';$('#objectives').value=m.objectives||'';scenesUI();status('Match plan loaded.')};d.querySelector('.danger').onclick=()=>{data.matches=data.matches.filter(x=>x.id!==m.id);save();matchesUI()};b.appendChild(d)})}
function all(){teamUI();rosterUI();draw();scenesUI();matchesUI();editor()}
function applyFormation(){team.formation=$('#formation').value;let c=coords(team.format,team.formation);board.players.forEach((p,i)=>{p.x=c[i]?.[0]||500;p.y=c[i]?.[1]||325});save();draw();status('Formation applied.')}
function opponent(){board.showOpponent=!board.showOpponent;if(board.showOpponent&&!board.opponents.length){let c=coords(team.format,team.formation);board.opponents=c.map((q,i)=>({id:'o'+i,x:1000-q[0],y:q[1],role:'OPP',number:i+1,name:''}))}draw()}
function snap(){return{name:($('#phaseName').value.trim()||`Phase ${scenes.length+1}`).slice(0,50),notes:$('#phaseNotes').value.slice(0,1000),board:structuredClone(board)}}
function anim(target,dur=900){return new Promise(res=>{let st=performance.now(),fp=structuredClone(board.players),fb={...board.ball};function step(now){if(!playing)return res();let t=clamp((now-st)/dur,0,1);t=t*t*(3-2*t);board.players.forEach((p,i)=>{let q=target.players.find(x=>x.id===p.id)||target.players[i]||p,a=fp[i]||p;p.x=a.x+(q.x-a.x)*t;p.y=a.y+(q.y-a.y)*t});board.ball.x=fb.x+(target.ball.x-fb.x)*t;board.ball.y=fb.y+(target.ball.y-fb.y)*t;draw();if(t<1)raf=requestAnimationFrame(step);else{board=structuredClone(target);res()}}raf=requestAnimationFrame(step)})}
async function play(){if(scenes.length<2)return status('Save at least two phases first.');if(playing)return;playing=true;for(let i=0;i<scenes.length&&playing;i++){activeScene=i;scenesUI();await anim(scenes[i].board);await new Promise(r=>setTimeout(r,350))}playing=false;status('Sequence complete.')}
$('#teamSelect').onchange=e=>{data.active=e.target.value;team=data.teams.find(t=>t.id===data.active);board=freshBoard();scenes=[];selected=null;save();all()};
$('#addTeam').onclick=()=>{let name=prompt('Team name');if(!name)return;let fmt=prompt('Format: 11v11, 9v9, 8v8, 7v7, 6v6, or 5v5','7v7');if(!formats[fmt])return status('Unsupported format.');let id='t'+Date.now(),t=mkTeam(id,name,fmt,formats[fmt].f[0],formats[fmt].n+3);data.teams.push(t);data.active=id;team=t;board=freshBoard();scenes=[];save();all()};
$('#delTeam').onclick=()=>{if(data.teams.length===1)return status('Keep at least one team.');if(!confirm(`Delete ${team.name}?`))return;data.teams=data.teams.filter(t=>t.id!==team.id);team=data.teams[0];data.active=team.id;board=freshBoard();scenes=[];save();all()};
$('#teamName').onchange=e=>{team.name=e.target.value.trim().slice(0,50)||team.name;save();teamUI()};$('#format').onchange=e=>{team.format=e.target.value;team.formation=formats[team.format].f[0];while(team.players.length<formats[team.format].n)team.players.push({id:team.id+'p'+Date.now()+team.players.length,name:'',role:'P'+team.players.length,number:team.players.length+1});board=freshBoard();scenes=[];save();all()};$('#formation').onchange=applyFormation;$('#applyFormation').onclick=applyFormation;$('#addPlayer').onclick=()=>{let i=team.players.length,p={id:team.id+'p'+Date.now(),name:'',role:'SUB',number:i+1};team.players.push(p);save();rosterUI()};$('#oppBtn').onclick=opponent;$('#laneBtn').onclick=()=>{board.laneMode=board.laneMode===5?3:board.laneMode===3?0:5;draw()};$('#bias').onchange=e=>{board.bias=e.target.value;draw()};
$('#savePhase').onclick=()=>{scenes.push(snap());activeScene=scenes.length-1;scenesUI();status('Phase saved.')};$('#play').onclick=play;$('#stop').onclick=()=>{playing=false;if(raf)cancelAnimationFrame(raf);status('Animation stopped.')};
$('#pName').oninput=e=>{let p=board.players.find(x=>x.id===selected),q=team.players.find(x=>x.id===selected);if(p){p.name=e.target.value.slice(0,24);if(q)q.name=p.name;save();draw();rosterUI()}};$('#pRole').oninput=e=>{let p=board.players.find(x=>x.id===selected),q=team.players.find(x=>x.id===selected);if(p){p.role=e.target.value.slice(0,12)||'P';if(q)q.role=p.role;save();draw();rosterUI()}};$('#pNum').oninput=e=>{let p=board.players.find(x=>x.id===selected),q=team.players.find(x=>x.id===selected);if(p){p.number=clamp(parseInt(e.target.value||0),0,99);if(q)q.number=p.number;save();draw();rosterUI()}};document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{let p=board.players.find(x=>x.id===selected);if(!p)return;let [dx,dy]=b.dataset.nudge.split(',').map(Number);p.x=clamp(p.x+dx,45,955);p.y=clamp(p.y+dy,45,605);draw()});
$('#saveMatch').onclick=()=>{let m={id:'m'+Date.now(),teamId:team.id,opponent:$('#matchOpponent').value.trim()||'Opponent',date:$('#matchDate').value,venue:$('#venue').value.trim(),objectives:$('#objectives').value,format:team.format,formation:team.formation,roster:structuredClone(team.players),scenes:structuredClone(scenes)};data.matches.unshift(m);save();matchesUI();status('Match plan saved.')};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='coach-tactics-pro-backup.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)};$('#importFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let o=JSON.parse(r.result);if(!o||!Array.isArray(o.teams))throw 0;data=o;team=data.teams[0];data.active=team.id;board=freshBoard();scenes=[];save();all();status('Backup imported.')}catch(_){status('Invalid backup file.')}};r.readAsText(f);e.target.value=''};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});all();status(navigator.onLine?'Ready · online':'Ready · offline');addEventListener('online',()=>status('Connection restored.'));addEventListener('offline',()=>status('Offline mode · local plans remain available.'))})();
